name: calendar
description: "Calendar App dengan Clean Architecture dan Google Calendar Integration"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Network & API
  dio: ^5.4.0
  json_annotation: ^4.9.0
  http: ^1.2.0
  
  # Google Calendar Integration
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  google_sign_in: ^6.2.1
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Dependency Injection
  get_it: ^7.6.7
  
  # Functional Programming
  dartz: ^0.10.1
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.3
  connectivity_plus: ^5.0.2
  
  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.8
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  # assets:
  #   - images/
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic